---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: concourse-pipeline-samples

outputs:
- name: current-app-info

run:
  path: concourse-glue-green-sample/ci/tasks/current-app-get-info
